--------------------------------------------------------
--  File created - Monday-November-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BET
--------------------------------------------------------

  CREATE TABLE "ANTE"."BET" 
   (	"BET_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"EVENT_CODE" CHAR(5 BYTE), 
	"TRANSACTION_CODE" CHAR(5 BYTE), 
	"COMPETITOR_ID" NUMBER, 
	"AMOUNT_BET" NUMBER(10,2), 
	"WINNINGS" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPETITOR
--------------------------------------------------------

  CREATE TABLE "ANTE"."COMPETITOR" 
   (	"COMPETITOR_ID" NUMBER, 
	"COMPETITOR_NAME" VARCHAR2(20 BYTE), 
	"EVENT_CODE" CHAR(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "ANTE"."EVENT" 
   (	"EVENT_CODE" CHAR(5 BYTE), 
	"EVENT_DATE" DATE, 
	"EVENT_TYPE" CHAR(4 BYTE), 
	"WINNER_ID" NUMBER, 
	"SETTLED" NUMBER(*,0) DEFAULT 0, 
	"DONE" NUMBER(*,0) DEFAULT 0, 
	"DRAW" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ANTE"."USERS" 
   (	"USER_ID" NUMBER, 
	"TYPE" NUMBER(*,0) DEFAULT 0, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER(10,2) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence BET_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ANTE"."BET_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMPETITOR_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ANTE"."COMPETITOR_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SQ
--------------------------------------------------------

   CREATE SEQUENCE  "ANTE"."USER_SQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into ANTE.BET
SET DEFINE OFF;
REM INSERTING into ANTE.COMPETITOR
SET DEFINE OFF;
REM INSERTING into ANTE.EVENT
SET DEFINE OFF;
REM INSERTING into ANTE.USERS
SET DEFINE OFF;
Insert into ANTE.USERS (USER_ID,TYPE,USERNAME,PASSWORD,FIRSTNAME,LASTNAME,BALANCE) values (1,1,'admin','admin',null,null,0);
--------------------------------------------------------
--  DDL for Index COMPETITOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANTE"."COMPETITOR_PK" ON "ANTE"."COMPETITOR" ("COMPETITOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANTE"."USERS_UK1" ON "ANTE"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANTE"."USERS_PK" ON "ANTE"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANTE"."BET_PK" ON "ANTE"."BET" ("BET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANTE"."EVENT_PK" ON "ANTE"."EVENT" ("EVENT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "ANTE"."EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("EVENT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANTE"."EVENT" MODIFY ("DRAW" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."EVENT" MODIFY ("DONE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."EVENT" MODIFY ("SETTLED" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."EVENT" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."EVENT" MODIFY ("EVENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."EVENT" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPETITOR
--------------------------------------------------------

  ALTER TABLE "ANTE"."COMPETITOR" ADD CONSTRAINT "COMPETITOR_PK" PRIMARY KEY ("COMPETITOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANTE"."COMPETITOR" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."COMPETITOR" MODIFY ("COMPETITOR_NAME" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."COMPETITOR" MODIFY ("COMPETITOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "ANTE"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANTE"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANTE"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."USERS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BET
--------------------------------------------------------

  ALTER TABLE "ANTE"."BET" MODIFY ("AMOUNT_BET" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."BET" MODIFY ("WINNINGS" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."BET" ADD CONSTRAINT "BET_PK" PRIMARY KEY ("BET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANTE"."BET" MODIFY ("COMPETITOR_ID" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."BET" MODIFY ("TRANSACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."BET" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."BET" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ANTE"."BET" MODIFY ("BET_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BET
--------------------------------------------------------

  ALTER TABLE "ANTE"."BET" ADD CONSTRAINT "BET_EVENTCODE_FK" FOREIGN KEY ("EVENT_CODE")
	  REFERENCES "ANTE"."EVENT" ("EVENT_CODE") ENABLE;
  ALTER TABLE "ANTE"."BET" ADD CONSTRAINT "BET_USERID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "ANTE"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPETITOR
--------------------------------------------------------

  ALTER TABLE "ANTE"."COMPETITOR" ADD CONSTRAINT "COMPETITOR_EVENTCODE_FK1" FOREIGN KEY ("EVENT_CODE")
	  REFERENCES "ANTE"."EVENT" ("EVENT_CODE") ENABLE;
